name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  run-build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.2
      - name: Build with Maven
        run: mvn clean install
      - name: Rename the artifact
        run: mv target/*.jar gestorinventario-${{github.sha}}.jar
      - name: Save the artifact
        uses: actions/upload-artifact@master
        with:
          name: gestorinventario
          path: gestorinventario-${{github.sha}}.jar

  fake-deploy:
    runs-on: self-hosted
    needs: run-build
    steps:
      - name: Get the artifact
        uses: actions/download-artifact@master
        with:
          name: gestorinventario
      - name: Fake deploy
        run: ls gestorinventario*.jar
